### PR TITLE
Enhanced React Native Detection

### PR DESCRIPTION
**Pull request by aancw**
Added:

- React native detection via index.android.bundle file
- Detecting React native hermes byte code version
- Added Jailmonkey root detection

### CODE REVIEW

**Comment by cryptax** [comment]
should be fine, thanks for the contribution. Never had a look at Hermes before.

**Comment by aancw** [comment]
Fyi, This patch doesn't include storing the results to database.

**Comment by cryptax** [comment]
I don't use the database very much any longer... might delete it one day.

**Comment by aancw** [comment]
I think the database will be helpful if you plan to use web base for viewing the result in more organized way

**Comment by cryptax** [comment]
yes, and it's useful if you process many files

**Pull request merged**
